### ISSUE TITLE
你好，是否可以留個郵箱聊一下蝦皮的爬蟲的事情呢?

### ISSUE THREAD

**Issue by no13bus** [AxotZero/ShopeeCrawler#1]
你好，是否可以留個郵箱聊一下蝦皮的爬蟲的事情呢?

我現在也在寫爬蟲相關的東西，想跟你諮詢下，怎麼能拿到蝦皮店鋪的列表呢？

**Comment by AxotZero** [comment]
不好意思，之前把Github通知關掉，導致現在才看到。
我其實對爬蟲也沒有很熟，只是某門課程數據分析課程要自己找資料分析所以試試看爬蟲看而已哈哈。

我程式碼的部分並沒有獲取賣家列表，而是針對單一商品獲得其賣家資訊，因為我是直接抓取網頁原始碼的資料，且賣家資訊要等js渲染才會出現，所以需要selenium模擬瀏覽器，並且給予每個商品頁面延遲n秒後才爬內容，便可抓到賣家的資訊。
之前有聽別人講可以直接抓取頁面api的部分，能夠省下許多時間，感覺是比較好的作法，不過我沒有深入去研究XD。

若有其他問題或要交流的話，我的email:asdswegreh@gmail.com
